import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "NEXT 프로젝트",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="ko"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header className="flex gap-5 border-b p-5">
          <Link href="/" className="font-bold">
            DevStudy
          </Link>
          <Link href="/dashboard">대시보드</Link>
          <Link href="/notes">학습노트</Link>
          <Link href="/about">About</Link>
        </header>

        {children}
      </body>
    </html>
  );
}
